---
# For manual installation, click here:
# https://hq.apiscp.com/updating-centos-7-in-place-with-leapp/

- name: Upgrade to AlmaLinux/Rocky Linux using Leapp
  hosts: all
  become: true
  tasks:
    - name: Download Leapp
      yum:
        name: "http://repo.almalinux.org/elevate/elevate-release-latest-el7.noarch.rpm"
        state: present

    - name: Install leapp-upgrade and leapp-data-almalinux
      yum:
        name: 'leapp-upgrade, leapp-data-almalinux'
        state: latest
        update_cache: true

    - name: Perform pre-upgrade check
      command: leapp preupgrade
      register: preupgrade_result
      ignore_errors: true

