---
- name: Install this packages
  hosts: all
  tasks:
    - name: Update remove_pam_pkcs11_module_check confirm value
      ansible.builtin.lineinfile:
        path: /var/log/leapp/answerfile
        regexp: '^confirm ='
        line: 'confirm = true'
        insertafter: '^# confirm ='

    - name: Acknowledge removal of pam_pkcs11
      command: leapp answer --section remove_pam_pkcs11_module_check.confirm=True

    - name: Upgrade system
      command: leapp upgrade

    - name: Reboot after upgrade
      raw: shutdown -r now
      ignore_unreachable: true
      ignore_errors: true
      
    - name: Wait for system to become reachable again
      wait_for_connection:
        delay: 240
        timeout: 1200

    - name: Cleanup any orphan packages from RHEL7
      command: rpm -qa | grep -E 'el7[.-]' | xargs rpm -e

    - name: Update the packages
      dnf:
        name: '*'
        state: latest
        update_cache: true
