---
- name: Clean up orphan packages
  hosts: all
  become: true
  tasks:
  - name: Cleanup any orphan packages from RHEL7
    command: rpm -qa | grep -E 'el7[.-]' | xargs rpm -e

  - name: Update the packages
    dnf:
      name: '*'
      state: latest
      update_cache: true

  - name: Reboot after upgrade
    raw: shutdown -r now
    ignore_unreachable: true
    ignore_errors: true

  - name: Wait for system to become reachable again
    wait_for_connection:
      delay: 240
      timeout: 1200
