---
- name: mlocate install
  hosts: dns.johnlord.comm
  become: true
  tasks:
    - name: install mlocate
      yum:
        name: mlocate
        state: latest
        update_cache: true
      tags:
        package
    - name: run updatedb
      command: updatedb
      become: true
