---
- name: Installing Nagios client
  hosts: all
  tasks:
  - name: install epel-release
    yum:
      name: epel-release
      state: latest

  - name: install nrpe
    yum:
      name: nrpe
      state: latest

  - name: install nagios plugins
    yum:
      name: nagios-plugins-all
      state: latest

  - name: deploy nrpe.cfg
    copy:
      src: nrpe.cfg
      dest: /etc/nagios/nrpe.cfg
    register: deploy_nrpe

  - name: Set up nagios firewall rules
    firewalld:
      port: 5666/tcp
      permanent: true
      state: enabled
  - name: reload firewalld
    command: firewall-cmd --reload

  - name:  Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive

  - name: start/restart and enable nrpe
    systemd:
      name: nrpe
      state: restarted
      enabled: yes
    when: deploy_nrpe.changed
