---
- name: Restart patched servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Restart after patching
      raw: shutdown -r now
      ignore_unreachable: true
      ignore_errors: true

    - name: Wait for system to become reachable again
      wait_for_connection:
        delay: 60
        timeout: 300
