---
- name: Install ubuntu updates
  hosts: sona-ubuntu.johnlord.comm
  become: true
  tasks:
  - name: Installing updates
    apt:
      name: "*"
      state: latest
      update_cache: true
  - name: Install package
    apt:
      name: vim,view,java,unzip
      state: present
     
