---
- name: Manage SSH keys for sysadm
  hosts: all
  become: yes
  tasks:
    - name: Add SSH authorized keys for sysadm
      authorized_keys:
        user: sysadm
        state: present
        key: "{{ item }}"
      with_items:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICXdALwxKv4ethwSA9ETK1lEe4U7bHUJrVNjMxXQx9b0z30c sysadm@ans.johnlord.comm
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv+OWaoyC9NkDdI31aITj79FkYJ0cm5zdEbmtEzHdu/NeAbt99FvGv6rV5ilY+o/uLQ134Wfg+masd9uMowZLrWWZ8dhz5jDNljowFvBs5UH49S0qcNAUPuAM+tv+EwW1rBGIatwGe91DT6OTlL0lk6F6vrpZodjOpCDj2H1mA7HVhbMRJJIjlx0RqIdUl/hVJwZUF6V+dNr5oIlibbAQCKmenec/kqxDA/m0uvhvHzpBpDQnvaX2nNbiRi71fWSVUFFg4ptwlhsMS+3r62ZqWc5wqqugQJc9HaEbnAoEN/jKXhlGKE5gY4uOvnviPuPWyq2a1WD+ZG7R7631cpobnYRIL sysadm@ans.johnlord.comm

