---
- name: update the system
  hosts: all
  tasks:
  - name: Install the packages
    yum:
      name: 'epel-release, vim, wget, unzip, java-11-openjdk-devel'
      state: present
      update_cache: true
    tags: packages

  - name: Download MySQL GPG Key
    become: yes
    get_url:
      url: https://dev.mysql.com/downloads/file/?id=527911
      dest: /tmp/RPM-GPG-KEY-mysql

  - name: Import MySQL GPG Key
    become: yes
    rpm_key:
      state: present
      key: /tmp/RPM-GPG-KEY-mysql

  #- name: Import GPG Keys if missing
  #  yum:
  #    name: https://dev.mysql.com/downloads/file/?id=527911
  #    state: present
  #    update_cache: true

  - name: update the system
    yum:
      name: "*"
      state: latest

  - name: Restart after patching
    raw: shutdown -r now
    ignore_unreachable: true
    ignore_errors: true
  - name: Wait for system to become reachable again
    wait_for_connection:
      delay: 60
      timeout: 300
